name: Tests

on:
  push:
    branches: ["ming/github-action"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1  
        with:
          bun-version: 1.1.4
      - name: Install dependencies
        run: bun install
      - name: Set up aiken
        uses: aiken-lang/setup-aiken@v1.0.2
        with:
          version: v1.0.26-alpha
      - run: aiken fmt --check
      - run: aiken check -D
      - run: aiken build -t verbose
      - run: bun gen-plutus
      - run: bun test
